
spring:
  application:
    name: catalogservice
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/CatalogFinalDB
      repositories:
        enabled: true

  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue
 
resilience4j:
  circuitbreaker:
    instances:
      errorcito:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      catalog:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
        
        
server:
  port: 8071

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
